# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python Build Macos

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: 	macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.7.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Pyinstaller
      run: pyinstaller --windowed --icon ./resources/icons/hexagon.icns --add-data "./resources/icons:resources/icons" --clean --noconfirm --collect-data pulp --onefile --noconsole --name GraphFilter-x.x.x-macos app.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: dist
